config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "static_pages#home"
  get 'static_pages/home'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :microposts,   only: [:new, :create, :destroy]
end

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
  crossorigin="anonymous">
<title>
  <%= full_title(yield(:title)) %>
</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" style="background-color:white;">
    <div class="container">
      <%= link_to "#ootd", root_path, class: "navbar-brand" %>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to "HOME", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "ABOUT", '#', class: "nav-link active" %>
        </li>
        <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
        <% if user_signed_in? %>
        <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
        <!-- *_path はUserモデルを作成したときに、deviseにより自動で作成されてますので、rake routesで確認できます -->
        <li class="nav-item">
          <%= link_to "ACOUNT", "#", class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "投稿する", new_micropost_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "LOGOUT", destroy_user_session_path, method: :delete , class: "nav-link active" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "SIGN UP", new_user_registration_path, class: "nav-link active"  %>
        </li>
        <li class="nav-item">
          <%= link_to "LOGIN", new_user_session_path, class: "nav-link active"  %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= javascript_include_tag 'application' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"></script>
  </body>

</html>